image: registry.meia8.com/john/node:8.7.0

stages:
- build
- deploy

variables:
  CONTAINER_REGISTRY: registry.meia8.com
  CONTAINER_DEVELOP_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:develop
  CONTAINER_DEVELOP_OLD_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:develop_old
  CONTAINER_RELEASE_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  CONTAINER_MASTER_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master
  CONTAINER_RELEASE_IMAGE_TAG: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
build-tags:
  stage: build
  script:
    - cnpm install
    - npm run build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_MASTER_IMAGE .
    - docker tag $CONTAINER_MASTER_IMAGE $CONTAINER_RELEASE_IMAGE_TAG
    - docker push $CONTAINER_MASTER_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE_TAG
  only:
  - tags
deploy-dev:
  stage: deploy
  script:
    - cnpm install
    - npm run build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_DEVELOP_IMAGE .
    - docker push $CONTAINER_DEVELOP_IMAGE
    - kubectl delete -f deployment.yaml
    - kubectl create -f deployment.yaml
  when: manual
  environment:
    name: staging
    url: https://app-dev.qms888.com/qms-c
  only:
  - develop
